runtime: python
python_version: "3.11"
services:
  - type: web
    name: Telegram Bot
    plan: free
    runtime: python3.11  # ← ВАЖНО: явно указываем версию!
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        fromFile: true
        secret: true
    secretFiles:
      - path: dialogflow-key.json
        name: dialogflow-key.json
